//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
MIT License

Copyright (c) 2021 Manabu Sonoda

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package common_configs

import (
	net "net"

	api "github.com/mimuret/golang-iij-dpf/pkg/api"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeMeta) DeepCopyInto(out *AttributeMeta) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeMeta.
func (in *AttributeMeta) DeepCopy() *AttributeMeta {
	if in == nil {
		return nil
	}
	out := new(AttributeMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CcPrimary) DeepCopyInto(out *CcPrimary) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CcPrimary.
func (in *CcPrimary) DeepCopy() *CcPrimary {
	if in == nil {
		return nil
	}
	out := new(CcPrimary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CcPrimary) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CcPrimaryList) DeepCopyInto(out *CcPrimaryList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CcPrimary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CcPrimaryList.
func (in *CcPrimaryList) DeepCopy() *CcPrimaryList {
	if in == nil {
		return nil
	}
	out := new(CcPrimaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CcPrimaryList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CcSecNotifiedServer) DeepCopyInto(out *CcSecNotifiedServer) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CcSecNotifiedServer.
func (in *CcSecNotifiedServer) DeepCopy() *CcSecNotifiedServer {
	if in == nil {
		return nil
	}
	out := new(CcSecNotifiedServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CcSecNotifiedServer) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CcSecNotifiedServerList) DeepCopyInto(out *CcSecNotifiedServerList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CcSecNotifiedServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CcSecNotifiedServerList.
func (in *CcSecNotifiedServerList) DeepCopy() *CcSecNotifiedServerList {
	if in == nil {
		return nil
	}
	out := new(CcSecNotifiedServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CcSecNotifiedServerList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CcSecTransferAcl) DeepCopyInto(out *CcSecTransferAcl) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CcSecTransferAcl.
func (in *CcSecTransferAcl) DeepCopy() *CcSecTransferAcl {
	if in == nil {
		return nil
	}
	out := new(CcSecTransferAcl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CcSecTransferAcl) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CcSecTransferAclList) DeepCopyInto(out *CcSecTransferAclList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CcSecTransferAcl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CcSecTransferAclList.
func (in *CcSecTransferAclList) DeepCopy() *CcSecTransferAclList {
	if in == nil {
		return nil
	}
	out := new(CcSecTransferAclList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CcSecTransferAclList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
