//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
MIT License

Copyright (c) 2021 Manabu Sonoda

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package contracts

import (
	api "github.com/mimuret/golang-iij-dpf/pkg/api"
	core "github.com/mimuret/golang-iij-dpf/pkg/apis/dpf/v1/core"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeMeta) DeepCopyInto(out *AttributeMeta) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeMeta.
func (in *AttributeMeta) DeepCopy() *AttributeMeta {
	if in == nil {
		return nil
	}
	out := new(AttributeMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonConfig) DeepCopyInto(out *CommonConfig) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonConfig.
func (in *CommonConfig) DeepCopy() *CommonConfig {
	if in == nil {
		return nil
	}
	out := new(CommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CommonConfig) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonConfigDefault) DeepCopyInto(out *CommonConfigDefault) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonConfigDefault.
func (in *CommonConfigDefault) DeepCopy() *CommonConfigDefault {
	if in == nil {
		return nil
	}
	out := new(CommonConfigDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CommonConfigDefault) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonConfigList) DeepCopyInto(out *CommonConfigList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	out.Count = in.Count
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CommonConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonConfigList.
func (in *CommonConfigList) DeepCopy() *CommonConfigList {
	if in == nil {
		return nil
	}
	out := new(CommonConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CommonConfigList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonConfigManagedDns) DeepCopyInto(out *CommonConfigManagedDns) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonConfigManagedDns.
func (in *CommonConfigManagedDns) DeepCopy() *CommonConfigManagedDns {
	if in == nil {
		return nil
	}
	out := new(CommonConfigManagedDns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *CommonConfigManagedDns) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractPartner) DeepCopyInto(out *ContractPartner) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractPartner.
func (in *ContractPartner) DeepCopy() *ContractPartner {
	if in == nil {
		return nil
	}
	out := new(ContractPartner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractPartnerList) DeepCopyInto(out *ContractPartnerList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContractPartner, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractPartnerList.
func (in *ContractPartnerList) DeepCopy() *ContractPartnerList {
	if in == nil {
		return nil
	}
	out := new(ContractPartnerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *ContractPartnerList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractZoneCommonConfig) DeepCopyInto(out *ContractZoneCommonConfig) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.ZoneIds != nil {
		in, out := &in.ZoneIds, &out.ZoneIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractZoneCommonConfig.
func (in *ContractZoneCommonConfig) DeepCopy() *ContractZoneCommonConfig {
	if in == nil {
		return nil
	}
	out := new(ContractZoneCommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *ContractZoneCommonConfig) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractZoneList) DeepCopyInto(out *ContractZoneList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	out.Count = in.Count
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]core.Zone, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractZoneList.
func (in *ContractZoneList) DeepCopy() *ContractZoneList {
	if in == nil {
		return nil
	}
	out := new(ContractZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *ContractZoneList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogList) DeepCopyInto(out *LogList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	out.Count = in.Count
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]core.Log, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogList.
func (in *LogList) DeepCopy() *LogList {
	if in == nil {
		return nil
	}
	out := new(LogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *LogList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QpsHistory) DeepCopyInto(out *QpsHistory) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]QpsValue, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QpsHistory.
func (in *QpsHistory) DeepCopy() *QpsHistory {
	if in == nil {
		return nil
	}
	out := new(QpsHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QpsHistoryList) DeepCopyInto(out *QpsHistoryList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QpsHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QpsHistoryList.
func (in *QpsHistoryList) DeepCopy() *QpsHistoryList {
	if in == nil {
		return nil
	}
	out := new(QpsHistoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *QpsHistoryList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QpsValue) DeepCopyInto(out *QpsValue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QpsValue.
func (in *QpsValue) DeepCopy() *QpsValue {
	if in == nil {
		return nil
	}
	out := new(QpsValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tsig) DeepCopyInto(out *Tsig) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tsig.
func (in *Tsig) DeepCopy() *Tsig {
	if in == nil {
		return nil
	}
	out := new(Tsig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *Tsig) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TsigCommonConfigList) DeepCopyInto(out *TsigCommonConfigList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	out.Count = in.Count
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CommonConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TsigCommonConfigList.
func (in *TsigCommonConfigList) DeepCopy() *TsigCommonConfigList {
	if in == nil {
		return nil
	}
	out := new(TsigCommonConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *TsigCommonConfigList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TsigList) DeepCopyInto(out *TsigList) {
	*out = *in
	out.AttributeMeta = in.AttributeMeta
	out.Count = in.Count
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tsig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TsigList.
func (in *TsigList) DeepCopy() *TsigList {
	if in == nil {
		return nil
	}
	out := new(TsigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new api.Object.
func (in *TsigList) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
